# -*- coding: utf-8 -*-
"""Day 5 Python B7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/183SIqL4bd1jBHBBW0Y54EB_geafSrBbW

# Assignment 1 Day 5
"""

Listy = []
n = int(input("Enter no. of elements in the list: "))
for i in range(0,n):
    element = int(input())
    Listy.append(element)
    
print("\nThe entered list is: " + str(list(Listy)))
lst = [1,1,5]
print("The sub list is: " + str(list(lst)))

flag = set(lst).issubset(set(Listy))
j = 0
for num in range (0,n):
    if Listy[num] == lst[j]:
        j = j + 1
    
if flag and j == 3: 
    print("\nIt's a Match !!")
else:
    print("\nIt's a Gone !!")

"""# Assignment 2 Day 5"""

def prime(n):
    for i in range(2,n):
        if n%i==0:
            return False
    else:return True
l=list(range(1,2500))
print(list(filter(prime,l)))

"""# Assignment 3 Day 5"""

lst = ["hey this is bhavana","i am in mumbai"]

getCapital = lambda sent: sent.upper()

newList = map(lambda sent: sent.upper(), lst)

print(list(newList))