# -*- coding: utf-8 -*-
"""Day 8 B7 Assignments.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bb4x7r2J_vqGix-SMmP9uu-Ab7Js4WZ_
"""



"""# Assignment 1 Day 8"""

#Q1.Write a decorator function for yur taking 
# input for you any kind of function you want to build,
#for example-You make a fibonacci series function,in which
#your input range is been defined by the decorator program input.


#solution:
def decorator_function(any_function):
  def wrapper_function(*args):
    print("Fibonacci Series for the given input")
    return any_function(*args)
  return wrapper_function


@decorator_function
def fibonacci_sqe(n):
    a = 0 # First number
    b = 1 # Second number
    if n == 1:
        print(a)
    elif n == 2:
        print(a,b)
    else:
        print(a,b, end=" ")
        for i in range(n-2):
            c = a + b
            a = b
            b = c
            print(b, end=" ")

x = int(input("Enter number: ")) 
print(fibonacci_sqe(x))

"""# Assignment 2"""

#Q2.For this challenge you to devlop a python program to open
#a file in read only mode and try writing somthing to it and 
# handle the subsequent errors using Exception handling.

#Solution:
try:
    file=open("MD.txt","r")
    file.write("This is my test file for exception handling!!!")
except IOError:
    print("can't find file or write data")
else:
    print("The file have been suceesfully read")
    file.close()