# -*- coding: utf-8 -*-
"""Day 6 B7 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qm86iCPiJpw7VdJQZhjaIXXDFqkaZnQ9

# Day 6 Batch 7 Assignment 1
"""

from math import *
print("Question1")
class Bank:
        def __init__(self,owner_name,balance):
            self.owner_name=owner_name
            self.balance=balance
            print("Happy Transactions!!!")
        def deposit(self):
            amount=float(input("Enter amount to be deposited"))
            self.balance+=amount
            print("Amount deposited")
            print("Current balance=",self.balance)
        def withdraw(self):
            amount=float(input("Enter amount to be withdrawn"))
            min_balance=500
            if (self.balance-amount)>=min_balance:
                d=self.balance-amount
                print("Amount Withdrawn")
            else:
                d=self.balance
                print("Minimum balance is expected..Please deposit")
            print("Current balance=",d)
b=Bank("Mr.XYZ",50000)
b.deposit()
b.withdraw()

"""# Day 6 Assignment 2"""

class cone:
    def __init__(self,radius,hieght):
        self.r=radius;
        self.h=hieght;
    def volume(self):
        vol=1/3*pi*(self.r**2)*self.h
        print("volume of cone=", vol)
    def surface_Area(self):
        sa=pi*self.r*(self.r+(sqrt((self.h**2)+ self.r**2)))
        print("surface area of cone=", sa)
cone=cone(4,3)
cone.volume()
cone.surface_Area()

